apiVersion: v1
kind: Service
metadata:
  name: mathapp-service
  namespace: k8s-mathapp-system
spec:
  selector:
    app: mathapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort

